' Simple System Health Tool - Combined Single-File Launcher
' Drop this .vbs anywhere and double-click to run.

Dim objShell, objFSO, strPS1, objFile

Set objShell = CreateObject("WScript.Shell")
Set objFSO   = CreateObject("Scripting.FileSystemObject")

' Write the embedded PS1 to a temp file
strPS1 = objFSO.GetSpecialFolder(2) & "\Simple_System_Health_Tool_GUI.ps1"
Set objFile = objFSO.CreateTextFile(strPS1, True, True)

objFile.WriteLine "#Requires -Version 5.1"
objFile.WriteLine "<#"
objFile.WriteLine ".SYNOPSIS    Simple System Health Tool - GUI Edition  v3.1"
objFile.WriteLine ".DESCRIPTION Graphical interface for common Windows maintenance tasks."
objFile.WriteLine "             Self-elevates to Administrator if needed."
objFile.WriteLine "             No compiled executables, no encoded commands."
objFile.WriteLine "#>"
objFile.WriteLine ""
objFile.WriteLine "# Catch any startup crash and show it in a popup instead of a vanishing console"
objFile.WriteLine "trap {"
objFile.WriteLine "    try {"
objFile.WriteLine "        Add-Type -AssemblyName System.Windows.Forms -ErrorAction SilentlyContinue"
objFile.WriteLine "        [System.Windows.Forms.MessageBox]::Show("
objFile.WriteLine "            ""Startup error:`n`n$($_.Exception.Message)`n`n$($_.InvocationInfo.PositionMessage)"","
objFile.WriteLine "            ""Simple System Health Tool - Error"", ""OK"", ""Error"") | Out-Null"
objFile.WriteLine "    } catch {"
objFile.WriteLine "        Write-Host ""FATAL: $($_.Exception.Message)"" -ForegroundColor Red"
objFile.WriteLine "    }"
objFile.WriteLine "    exit 1"
objFile.WriteLine "}"
objFile.WriteLine ""
objFile.WriteLine "Add-Type -AssemblyName System.Windows.Forms"
objFile.WriteLine "Add-Type -AssemblyName System.Drawing"
objFile.WriteLine "[System.Windows.Forms.Application]::EnableVisualStyles()"
objFile.WriteLine "[System.Windows.Forms.Application]::SetCompatibleTextRenderingDefault($false)"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# SELF-ELEVATE"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()"
objFile.WriteLine "if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {"
objFile.WriteLine "    $psPath = if ($PSCommandPath) { $PSCommandPath } else { $MyInvocation.MyCommand.Definition }"
objFile.WriteLine "    Start-Process powershell.exe `"
objFile.WriteLine "        -ArgumentList ""-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `""$psPath`"""" `"
objFile.WriteLine "        -Verb RunAs `"
objFile.WriteLine "        -WindowStyle Hidden"
objFile.WriteLine "    exit 0"
objFile.WriteLine "}"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# PATHS"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$ScriptDir  = if ($PSScriptRoot -and $PSScriptRoot -ne '') {"
objFile.WriteLine "    $PSScriptRoot"
objFile.WriteLine "} else {"
objFile.WriteLine "    Split-Path -Parent $MyInvocation.MyCommand.Definition"
objFile.WriteLine "}"
objFile.WriteLine "if (-not $ScriptDir -or -not (Test-Path $ScriptDir)) { $ScriptDir = $env:TEMP }"
objFile.WriteLine "$ReportPath = Join-Path $ScriptDir ""$($env:COMPUTERNAME)SystemHealth.txt"""
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# INTER-THREAD MESSAGE QUEUE"
objFile.WriteLine "# Message format: single-char type + ""|"" + text"
objFile.WriteLine "#   H=header (cyan)  P=pass (green)  F=fail (red)  E=error (red)"
objFile.WriteLine "#   D=detail (dim)   I=info (white)"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$script:MsgQueue = [System.Collections.Concurrent.ConcurrentQueue[string]]::new()"
objFile.WriteLine "$script:IsBusy   = $false"
objFile.WriteLine "$script:PSInst   = $null"
objFile.WriteLine "$script:RS       = $null"
objFile.WriteLine "$script:Handle   = $null"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# REPORT  (called on UI thread only)"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "function Initialize-Report {"
objFile.WriteLine "    if (Test-Path $ReportPath) { return }"
objFile.WriteLine "    $sep  = ""="" * 79"
objFile.WriteLine "    $rows = [System.Collections.Generic.List[string]]::new()"
objFile.WriteLine "    $rows.Add($sep)"
objFile.WriteLine "    $rows.Add(""$($env:COMPUTERNAME) System Health Report"")"
objFile.WriteLine "    $rows.Add($sep)"
objFile.WriteLine "    $rows.Add(""Computer Name : $($env:COMPUTERNAME)"")"
objFile.WriteLine "    try {"
objFile.WriteLine "        $reg = Get-ItemProperty ""HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion"" -EA Stop"
objFile.WriteLine "        $rows.Add(""Windows       : $($reg.ProductName)"")"
objFile.WriteLine "        $rows.Add(""Version       : $($reg.DisplayVersion)"")"
objFile.WriteLine "        $rows.Add(""Build         : $($reg.CurrentBuild)"")"
objFile.WriteLine "    } catch {}"
objFile.WriteLine "    try {"
objFile.WriteLine "        $sn = (Get-CimInstance Win32_BIOS -EA Stop).SerialNumber.Trim()"
objFile.WriteLine "        if ($sn -and $sn -notmatch ""O\.E\.M|^\s*$"") { $rows.Add(""Serial Number : $sn"") }"
objFile.WriteLine "    } catch {}"
objFile.WriteLine "    try {"
objFile.WriteLine "        $pk = (Get-CimInstance -Query ""SELECT OA3xOriginalProductKey FROM SoftwareLicensingService"" -EA Stop).OA3xOriginalProductKey"
objFile.WriteLine "        if ($pk) { $rows.Add(""License Key   : $pk"") } else { $rows.Add(""License Key   : Not found or not exposed."") }"
objFile.WriteLine "    } catch { $rows.Add(""License Key   : Not found or not exposed."") }"
objFile.WriteLine "    $rows.Add(""Created       : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"")"
objFile.WriteLine "    $rows.Add($sep)"
objFile.WriteLine "    $rows.Add("""")"
objFile.WriteLine "    [IO.File]::WriteAllLines($ReportPath, $rows, [Text.Encoding]::UTF8)"
objFile.WriteLine "}"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# BACKGROUND TASK SCRIPT"
objFile.WriteLine "# Variables injected via runspace SetVariable:"
objFile.WriteLine "#   $Queue       ConcurrentQueue[string]"
objFile.WriteLine "#   $ReportPath  string"
objFile.WriteLine "#   $TaskName    string"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$BackgroundScript = @'"
objFile.WriteLine "function Write-Section([string]$Title) {"
objFile.WriteLine "    $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'"
objFile.WriteLine "    [IO.File]::AppendAllText($ReportPath,"
objFile.WriteLine "        ""`n$(""-"" * 79)`n[$ts] $Title`n"", [Text.Encoding]::UTF8)"
objFile.WriteLine "}"
objFile.WriteLine "function Write-Result([string]$Result, [int]$Code, [string]$Msg) {"
objFile.WriteLine "    [IO.File]::AppendAllText($ReportPath,"
objFile.WriteLine "        ""Result    : $Result`nExit Code : $Code`nMessage   : $Msg`n"","
objFile.WriteLine "        [Text.Encoding]::UTF8)"
objFile.WriteLine "}"
objFile.WriteLine "function Invoke-Step([string]$Title, [string]$CmdLine) {"
objFile.WriteLine "    Write-Section $Title"
objFile.WriteLine "    $Queue.Enqueue(""I|  $Title"")"
objFile.WriteLine "    try {"
objFile.WriteLine "        $si = New-Object System.Diagnostics.ProcessStartInfo"
objFile.WriteLine "        $si.FileName               = ""cmd.exe"""
objFile.WriteLine "        $si.Arguments              = ""/c $CmdLine"""
objFile.WriteLine "        $si.RedirectStandardOutput = $true"
objFile.WriteLine "        $si.RedirectStandardError  = $true"
objFile.WriteLine "        $si.UseShellExecute        = $false"
objFile.WriteLine "        $si.CreateNoWindow         = $true"
objFile.WriteLine ""
objFile.WriteLine "        $proc = [System.Diagnostics.Process]::Start($si)"
objFile.WriteLine "        $out  = $proc.StandardOutput.ReadToEnd()"
objFile.WriteLine "        $err  = $proc.StandardError.ReadToEnd()"
objFile.WriteLine "        $proc.WaitForExit()"
objFile.WriteLine "        $rc   = $proc.ExitCode"
objFile.WriteLine ""
objFile.WriteLine "        $combined = ($out + $err).Trim()"
objFile.WriteLine "        foreach ($ln in ($combined -split ""`r?`n"")) {"
objFile.WriteLine "            if ($ln.Trim()) { $Queue.Enqueue(""D|    $ln"") }"
objFile.WriteLine "        }"
objFile.WriteLine "        $last = ($combined -split ""`r?`n"" |"
objFile.WriteLine "                 Where-Object { $_.Trim() } | Select-Object -Last 1)"
objFile.WriteLine "        if (-not $last) { $last = ""(no output)"" }"
objFile.WriteLine ""
objFile.WriteLine "        $res = if ($rc -eq 0) { ""PASS"" } else { ""FAIL"" }"
objFile.WriteLine "        Write-Result $res $rc $last"
objFile.WriteLine "        if ($rc -eq 0) { $Queue.Enqueue(""P|    [PASS] Exit code: $rc"") }"
objFile.WriteLine "        else           { $Queue.Enqueue(""F|    [FAIL] Exit code: $rc"") }"
objFile.WriteLine "        $Queue.Enqueue(""I|"")"
objFile.WriteLine "    } catch {"
objFile.WriteLine "        Write-Result ""FAIL"" -1 $_.Exception.Message"
objFile.WriteLine "        $Queue.Enqueue(""E|    [ERROR] $($_.Exception.Message)"")"
objFile.WriteLine "        $Queue.Enqueue(""I|"")"
objFile.WriteLine "    }"
objFile.WriteLine "}"
objFile.WriteLine ""
objFile.WriteLine "switch ($TaskName) {"
objFile.WriteLine "    ""PrintSpooler"" {"
objFile.WriteLine "        $Queue.Enqueue(""H|-- Reset Print Spooler ------------------------------------------------------"")"
objFile.WriteLine "        Invoke-Step ""Stop Print Spooler""  ""net stop spooler"""
objFile.WriteLine "        $q = ""$env:SystemRoot\System32\spool\PRINTERS"""
objFile.WriteLine "        if (Test-Path $q) {"
objFile.WriteLine "            Remove-Item ""$q\*"" -Force -ErrorAction SilentlyContinue"
objFile.WriteLine "            $Queue.Enqueue(""D|    Print queue cleared."")"
objFile.WriteLine "        }"
objFile.WriteLine "        Invoke-Step ""Start Print Spooler"" ""net start spooler"""
objFile.WriteLine "    }"
objFile.WriteLine "    ""NetworkReset"" {"
objFile.WriteLine "        $Queue.Enqueue(""H|-- Reset Network -----------------------------------------------------------"")"
objFile.WriteLine "        Invoke-Step ""Disable Physical Adapters"" 'wmic path win32_networkadapter where ""NetEnabled=true and PhysicalAdapter=true"" call disable'"
objFile.WriteLine "        Invoke-Step ""Enable Physical Adapters""  'wmic path win32_networkadapter where ""PhysicalAdapter=true"" call enable'"
objFile.WriteLine "        Invoke-Step ""Release and Renew IP""       ""ipconfig /release & ipconfig /renew"""
objFile.WriteLine "        Invoke-Step ""Flush DNS Cache""            ""ipconfig /flushdns"""
objFile.WriteLine "        Invoke-Step ""Reset Winsock Catalog""      ""netsh winsock reset"""
objFile.WriteLine "        Invoke-Step ""Reset TCP/IP Stack""         ""netsh int ip reset"""
objFile.WriteLine "    }"
objFile.WriteLine "    ""SystemCheck"" {"
objFile.WriteLine "        $Queue.Enqueue(""H|-- System Check ------------------------------------------------------------"")"
objFile.WriteLine "        $Queue.Enqueue(""I|  Note: DISM RestoreHealth may take 10-20 minutes."")"
objFile.WriteLine "        Invoke-Step ""DISM RestoreHealth"" ""DISM /Online /Cleanup-Image /RestoreHealth"""
objFile.WriteLine "        Invoke-Step ""SFC Scan""           ""sfc /scannow"""
objFile.WriteLine "        Invoke-Step ""CHKDSK C: Scan""    ""chkdsk C: /scan"""
objFile.WriteLine "    }"
objFile.WriteLine "    ""WindowsUpdate"" {"
objFile.WriteLine "        $Queue.Enqueue(""H|-- Reset Windows Update -----------------------------------------------------"")"
objFile.WriteLine "        $cmd = ""net stop wuauserv & net stop bits & net stop cryptsvc & net stop msiserver & "" +"
objFile.WriteLine "               ""ren C:\Windows\SoftwareDistribution SoftwareDistribution.old 2>nul & "" +"
objFile.WriteLine "               ""ren C:\Windows\System32\catroot2 catroot2.old 2>nul & "" +"
objFile.WriteLine "               ""net start msiserver & net start cryptsvc & net start bits & net start wuauserv"""
objFile.WriteLine "        Invoke-Step ""Reset Windows Update"" $cmd"
objFile.WriteLine "    }"
objFile.WriteLine "    ""MemoryDiag"" {"
objFile.WriteLine "        $Queue.Enqueue(""H|-- Windows Memory Diagnostic -----------------------------------------------"")"
objFile.WriteLine "        $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'"
objFile.WriteLine "        [IO.File]::AppendAllText($ReportPath,"
objFile.WriteLine "            ""`n$(""-""*79)`n[$ts] Windows Memory Diagnostic`n"", [Text.Encoding]::UTF8)"
objFile.WriteLine "        try {"
objFile.WriteLine "            Start-Process mdsched.exe"
objFile.WriteLine "            [IO.File]::AppendAllText($ReportPath,"
objFile.WriteLine "                ""Result    : PASS`nExit Code : 0`nMessage   : Launched.`n"","
objFile.WriteLine "                [Text.Encoding]::UTF8)"
objFile.WriteLine "            $Queue.Enqueue(""P|    [PASS] Windows Memory Diagnostic launched."")"
objFile.WriteLine "            $Queue.Enqueue(""D|    You can schedule the test from the dialog that appeared."")"
objFile.WriteLine "        } catch {"
objFile.WriteLine "            [IO.File]::AppendAllText($ReportPath,"
objFile.WriteLine "                ""Result    : FAIL`nExit Code : -1`nMessage   : $($_.Exception.Message)`n"","
objFile.WriteLine "                [Text.Encoding]::UTF8)"
objFile.WriteLine "            $Queue.Enqueue(""E|    [ERROR] $($_.Exception.Message)"")"
objFile.WriteLine "        }"
objFile.WriteLine "        $Queue.Enqueue(""I|"")"
objFile.WriteLine "    }"
objFile.WriteLine "    ""UnFuck"" {"
objFile.WriteLine "        $Queue.Enqueue(""H|== UnFuck - Full Repair Sequence ==========================================="")"
objFile.WriteLine "        $Queue.Enqueue(""I|  This may take 20-45 minutes. The window stays responsive throughout."")"
objFile.WriteLine "        $Queue.Enqueue(""I|"")"
objFile.WriteLine "        Invoke-Step ""DISM CheckHealth""   ""DISM /Online /Cleanup-Image /CheckHealth"""
objFile.WriteLine "        Invoke-Step ""DISM ScanHealth""    ""DISM /Online /Cleanup-Image /ScanHealth"""
objFile.WriteLine "        Invoke-Step ""DISM RestoreHealth"" ""DISM /Online /Cleanup-Image /RestoreHealth"""
objFile.WriteLine "        Invoke-Step ""SFC Scan""           ""sfc /scannow"""
objFile.WriteLine "        Invoke-Step ""CHKDSK C: Scan""    ""chkdsk C: /scan"""
objFile.WriteLine "        Invoke-Step ""Component Cleanup""  ""DISM /Online /Cleanup-Image /StartComponentCleanup"""
objFile.WriteLine "        $upd = ""net stop wuauserv & net stop bits & net stop cryptsvc & net stop msiserver & "" +"
objFile.WriteLine "               ""ren C:\Windows\SoftwareDistribution SoftwareDistribution.old 2>nul & "" +"
objFile.WriteLine "               ""ren C:\Windows\System32\catroot2 catroot2.old 2>nul & "" +"
objFile.WriteLine "               ""net start msiserver & net start cryptsvc & net start bits & net start wuauserv"""
objFile.WriteLine "        Invoke-Step ""Reset Windows Update"" $upd"
objFile.WriteLine "        Invoke-Step ""Stop Print Spooler""  ""net stop spooler"""
objFile.WriteLine "        $q = ""$env:SystemRoot\System32\spool\PRINTERS"""
objFile.WriteLine "        if (Test-Path $q) {"
objFile.WriteLine "            Remove-Item ""$q\*"" -Force -ErrorAction SilentlyContinue"
objFile.WriteLine "            $Queue.Enqueue(""D|    Print queue cleared."")"
objFile.WriteLine "        }"
objFile.WriteLine "        Invoke-Step ""Start Print Spooler"" ""net start spooler"""
objFile.WriteLine "        Invoke-Step ""Flush DNS""           ""ipconfig /flushdns"""
objFile.WriteLine "        Invoke-Step ""Reset Winsock""       ""netsh winsock reset"""
objFile.WriteLine "        Invoke-Step ""Reset TCP/IP""        ""netsh int ip reset"""
objFile.WriteLine "    }"
objFile.WriteLine "}"
objFile.WriteLine "'@"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# START TASK  (UI thread)"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "function Start-Task([string]$TaskName) {"
objFile.WriteLine "    if ($script:IsBusy) {"
objFile.WriteLine "        [Windows.Forms.MessageBox]::Show("
objFile.WriteLine "            ""An operation is already running.`nPlease wait for it to complete."","
objFile.WriteLine "            ""Busy"", ""OK"", ""Warning"") | Out-Null"
objFile.WriteLine "        return"
objFile.WriteLine "    }"
objFile.WriteLine "    Initialize-Report"
objFile.WriteLine ""
objFile.WriteLine "    $script:IsBusy    = $true"
objFile.WriteLine "    $statusLabel.Text = ""Running: $TaskName ..."""
objFile.WriteLine "    foreach ($b in $script:AllButtons) { $b.Enabled = $false }"
objFile.WriteLine ""
objFile.WriteLine "    $script:RS = [RunspaceFactory]::CreateRunspace()"
objFile.WriteLine "    $script:RS.ApartmentState = ""STA"""
objFile.WriteLine "    $script:RS.ThreadOptions  = ""ReuseThread"""
objFile.WriteLine "    $script:RS.Open()"
objFile.WriteLine "    $script:RS.SessionStateProxy.SetVariable(""Queue"",      $script:MsgQueue)"
objFile.WriteLine "    $script:RS.SessionStateProxy.SetVariable(""ReportPath"", $ReportPath)"
objFile.WriteLine "    $script:RS.SessionStateProxy.SetVariable(""TaskName"",   $TaskName)"
objFile.WriteLine ""
objFile.WriteLine "    $script:PSInst = [PowerShell]::Create()"
objFile.WriteLine "    $script:PSInst.Runspace = $script:RS"
objFile.WriteLine "    [void]$script:PSInst.AddScript($BackgroundScript)"
objFile.WriteLine "    $script:Handle = $script:PSInst.BeginInvoke()"
objFile.WriteLine "}"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# COLORS"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$cBG      = [Drawing.Color]::FromArgb(15, 15, 18)"
objFile.WriteLine "$cPanel   = [Drawing.Color]::FromArgb(24, 24, 28)"
objFile.WriteLine "$cLog     = [Drawing.Color]::FromArgb(10, 10, 12)"
objFile.WriteLine "$cFG      = [Drawing.Color]::FromArgb(210, 210, 218)"
objFile.WriteLine "$cDim     = [Drawing.Color]::FromArgb(95, 95, 110)"
objFile.WriteLine "$cBtnN    = [Drawing.Color]::FromArgb(38, 38, 45)"
objFile.WriteLine "$cBtnH    = [Drawing.Color]::FromArgb(55, 55, 64)"
objFile.WriteLine "$cGreen   = [Drawing.Color]::FromArgb(45, 200, 90)"
objFile.WriteLine "$cRed     = [Drawing.Color]::FromArgb(220, 58, 48)"
objFile.WriteLine "$cCyan    = [Drawing.Color]::FromArgb(70, 185, 230)"
objFile.WriteLine "$cDanger  = [Drawing.Color]::FromArgb(160, 28, 20)"
objFile.WriteLine "$cDangerH = [Drawing.Color]::FromArgb(195, 48, 36)"
objFile.WriteLine "$cStatus  = [Drawing.Color]::FromArgb(0, 68, 128)"
objFile.WriteLine "$cSep     = [Drawing.Color]::FromArgb(46, 46, 56)"
objFile.WriteLine "$cWhite   = [Drawing.Color]::White"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# FONTS"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$fMono  = New-Object Drawing.Font(""Consolas"",  9)"
objFile.WriteLine "$fUI    = New-Object Drawing.Font(""Segoe UI"",  9.5)"
objFile.WriteLine "$fUIB   = New-Object Drawing.Font(""Segoe UI"",  9.5, [Drawing.FontStyle]::Bold)"
objFile.WriteLine "$fTitle = New-Object Drawing.Font(""Segoe UI"",  12,  [Drawing.FontStyle]::Bold)"
objFile.WriteLine "$fSm    = New-Object Drawing.Font(""Segoe UI"",  8)"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# FORM"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$form = New-Object Windows.Forms.Form"
objFile.WriteLine "$form.Text          = ""Simple System Health Tool"""
objFile.WriteLine "$form.Size          = New-Object Drawing.Size(1000, 670)"
objFile.WriteLine "$form.MinimumSize   = New-Object Drawing.Size(820,  540)"
objFile.WriteLine "$form.StartPosition = ""CenterScreen"""
objFile.WriteLine "$form.BackColor     = $cBG"
objFile.WriteLine "$form.ForeColor     = $cFG"
objFile.WriteLine "$form.Font          = $fUI"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# LEFT PANEL  (fixed-width, absolute layout)"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$pLeft           = New-Object Windows.Forms.Panel"
objFile.WriteLine "$pLeft.Dock      = ""Left"""
objFile.WriteLine "$pLeft.Width     = 276"
objFile.WriteLine "$pLeft.BackColor = $cPanel"
objFile.WriteLine ""
objFile.WriteLine "# Title label"
objFile.WriteLine "$lTitle           = New-Object Windows.Forms.Label"
objFile.WriteLine "$lTitle.Text      = ""SYSTEM HEALTH"""
objFile.WriteLine "$lTitle.Font      = $fTitle"
objFile.WriteLine "$lTitle.ForeColor = $cFG"
objFile.WriteLine "$lTitle.AutoSize  = $false"
objFile.WriteLine "$lTitle.Bounds    = [Drawing.Rectangle]::new(16, 18, 244, 28)"
objFile.WriteLine "$pLeft.Controls.Add($lTitle)"
objFile.WriteLine ""
objFile.WriteLine "# Admin badge"
objFile.WriteLine "$lAdmin           = New-Object Windows.Forms.Label"
objFile.WriteLine "$lAdmin.Text      = ""  Running as Administrator"""
objFile.WriteLine "$lAdmin.Font      = $fSm"
objFile.WriteLine "$lAdmin.ForeColor = $cGreen"
objFile.WriteLine "$lAdmin.AutoSize  = $false"
objFile.WriteLine "$lAdmin.Bounds    = [Drawing.Rectangle]::new(14, 50, 244, 16)"
objFile.WriteLine "$pLeft.Controls.Add($lAdmin)"
objFile.WriteLine ""
objFile.WriteLine "# Separator helper"
objFile.WriteLine "function Add-Separator {"
objFile.WriteLine "    param($Panel, $Y)"
objFile.WriteLine "    $s           = New-Object Windows.Forms.Panel"
objFile.WriteLine "    $s.Bounds    = [Drawing.Rectangle]::new(14, $Y, 246, 1)"
objFile.WriteLine "    $s.BackColor = $cSep"
objFile.WriteLine "    $Panel.Controls.Add($s) | Out-Null"
objFile.WriteLine "}"
objFile.WriteLine "Add-Separator $pLeft 74"
objFile.WriteLine ""
objFile.WriteLine "# ------------------------------------------------------------------"
objFile.WriteLine "# Action buttons"
objFile.WriteLine "# ------------------------------------------------------------------"
objFile.WriteLine "# Each entry: Label text, TaskName key, Description, IsDanger"
objFile.WriteLine "$btnDefs = @("
objFile.WriteLine "    @{ L=""1   Reset Print Spooler"";  K=""PrintSpooler""; D=""Restart print service, clear queue"";     Red=$false },"
objFile.WriteLine "    @{ L=""2   Reset Network"";        K=""NetworkReset"";  D=""Reset adapters, IP, DNS and Winsock"";    Red=$false },"
objFile.WriteLine "    @{ L=""3   System Check"";         K=""SystemCheck"";   D=""DISM RestoreHealth + SFC + CHKDSK"";      Red=$false },"
objFile.WriteLine "    @{ L=""4   Reset Windows Update""; K=""WindowsUpdate""; D=""Reset update services and cache"";        Red=$false },"
objFile.WriteLine "    @{ L=""5   Memory Diagnostic"";    K=""MemoryDiag"";    D=""Open the memory test scheduler"";         Red=$false },"
objFile.WriteLine "    @{ L=""6   UnFuck"";               K=""UnFuck"";        D=""Full repair sequence  (20-45 min)"";       Red=$true  }"
objFile.WriteLine ")"
objFile.WriteLine ""
objFile.WriteLine "$actionBtns = @{}"
objFile.WriteLine "$yPos = 84"
objFile.WriteLine ""
objFile.WriteLine "foreach ($def in $btnDefs) {"
objFile.WriteLine "    $bgNorm  = if ($def.Red) { $cDanger  } else { $cBtnN }"
objFile.WriteLine "    $bgHover = if ($def.Red) { $cDangerH } else { $cBtnH }"
objFile.WriteLine ""
objFile.WriteLine "    $btn = New-Object Windows.Forms.Button"
objFile.WriteLine "    $btn.Text      = $def.L"
objFile.WriteLine "    $btn.Font      = $fUIB"
objFile.WriteLine "    $btn.FlatStyle = ""Flat"""
objFile.WriteLine "    $btn.Bounds    = [Drawing.Rectangle]::new(14, $yPos, 248, 34)"
objFile.WriteLine "    $btn.TextAlign = ""MiddleLeft"""
objFile.WriteLine "    $btn.Padding   = New-Object Windows.Forms.Padding(10, 0, 0, 0)"
objFile.WriteLine "    $btn.Cursor    = [Windows.Forms.Cursors]::Hand"
objFile.WriteLine "    $btn.Tag       = $def.K"
objFile.WriteLine "    $btn.BackColor = $bgNorm"
objFile.WriteLine "    $btn.ForeColor = $cFG"
objFile.WriteLine "    $btn.FlatAppearance.BorderSize         = 0"
objFile.WriteLine "    $btn.FlatAppearance.MouseOverBackColor = $bgHover"
objFile.WriteLine "    # param($s,$e) ensures correct sender reference on all PS versions"
objFile.WriteLine "    $btn.Add_Click({"
objFile.WriteLine "        param($s, $e)"
objFile.WriteLine "        Start-Task $s.Tag"
objFile.WriteLine "    })"
objFile.WriteLine "    $pLeft.Controls.Add($btn) | Out-Null"
objFile.WriteLine ""
objFile.WriteLine "    $lDesc           = New-Object Windows.Forms.Label"
objFile.WriteLine "    $lDesc.Text      = $def.D"
objFile.WriteLine "    $lDesc.Font      = $fSm"
objFile.WriteLine "    $lDesc.ForeColor = $cDim"
objFile.WriteLine "    $lDesc.Bounds    = [Drawing.Rectangle]::new(24, ($yPos + 36), 238, 14)"
objFile.WriteLine "    $pLeft.Controls.Add($lDesc) | Out-Null"
objFile.WriteLine ""
objFile.WriteLine "    $actionBtns[$def.K] = $btn"
objFile.WriteLine "    $yPos += 57"
objFile.WriteLine "}"
objFile.WriteLine ""
objFile.WriteLine "Add-Separator $pLeft ($yPos + 6)"
objFile.WriteLine "$yPos += 18"
objFile.WriteLine ""
objFile.WriteLine "# Open Report button"
objFile.WriteLine "$btnReport           = New-Object Windows.Forms.Button"
objFile.WriteLine "$btnReport.Text      = ""Open Report File"""
objFile.WriteLine "$btnReport.Font      = $fUI"
objFile.WriteLine "$btnReport.FlatStyle = ""Flat"""
objFile.WriteLine "$btnReport.Bounds    = [Drawing.Rectangle]::new(14, $yPos, 248, 30)"
objFile.WriteLine "$btnReport.BackColor = $cBtnN"
objFile.WriteLine "$btnReport.ForeColor = $cFG"
objFile.WriteLine "$btnReport.FlatAppearance.BorderSize         = 0"
objFile.WriteLine "$btnReport.FlatAppearance.MouseOverBackColor = $cBtnH"
objFile.WriteLine "$btnReport.Cursor    = [Windows.Forms.Cursors]::Hand"
objFile.WriteLine "$btnReport.Add_Click({"
objFile.WriteLine "    Initialize-Report"
objFile.WriteLine "    Start-Process notepad.exe -ArgumentList ""`""$ReportPath`"""""
objFile.WriteLine "})"
objFile.WriteLine "$pLeft.Controls.Add($btnReport) | Out-Null"
objFile.WriteLine "$yPos += 38"
objFile.WriteLine ""
objFile.WriteLine "# Exit button"
objFile.WriteLine "$btnExit           = New-Object Windows.Forms.Button"
objFile.WriteLine "$btnExit.Text      = ""Exit"""
objFile.WriteLine "$btnExit.Font      = $fUI"
objFile.WriteLine "$btnExit.FlatStyle = ""Flat"""
objFile.WriteLine "$btnExit.Bounds    = [Drawing.Rectangle]::new(14, $yPos, 248, 30)"
objFile.WriteLine "$btnExit.BackColor = $cBtnN"
objFile.WriteLine "$btnExit.ForeColor = $cDim"
objFile.WriteLine "$btnExit.FlatAppearance.BorderSize         = 0"
objFile.WriteLine "$btnExit.FlatAppearance.MouseOverBackColor = $cBtnH"
objFile.WriteLine "$btnExit.Cursor    = [Windows.Forms.Cursors]::Hand"
objFile.WriteLine "$btnExit.Add_Click({"
objFile.WriteLine "    if ($script:IsBusy) {"
objFile.WriteLine "        $r = [Windows.Forms.MessageBox]::Show("
objFile.WriteLine "            ""An operation is still running.`nExit anyway?"","
objFile.WriteLine "            ""Confirm Exit"", ""YesNo"", ""Warning"")"
objFile.WriteLine "        if ($r -ne ""Yes"") { return }"
objFile.WriteLine "    }"
objFile.WriteLine "    $pollingTimer.Stop()"
objFile.WriteLine "    $form.Close()"
objFile.WriteLine "})"
objFile.WriteLine "$pLeft.Controls.Add($btnExit) | Out-Null"
objFile.WriteLine ""
objFile.WriteLine "# All buttons (for enable/disable toggling while busy)"
objFile.WriteLine "$script:AllButtons = [System.Collections.Generic.List[System.Windows.Forms.Button]]::new()"
objFile.WriteLine "$script:AllButtons.Add($btnReport)"
objFile.WriteLine "$script:AllButtons.Add($btnExit)"
objFile.WriteLine "foreach ($b in $actionBtns.Values) { $script:AllButtons.Add($b) }"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# RIGHT PANEL  (log output)"
objFile.WriteLine "# IMPORTANT: add Top-docked header FIRST, then Fill-docked log box."
objFile.WriteLine "# WinForms docks in Controls collection order, so Top must come before Fill."
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$pRight           = New-Object Windows.Forms.Panel"
objFile.WriteLine "$pRight.Dock      = ""Fill"""
objFile.WriteLine "$pRight.BackColor = $cBG"
objFile.WriteLine ""
objFile.WriteLine "$lLogHdr           = New-Object Windows.Forms.Label"
objFile.WriteLine "$lLogHdr.Text      = ""  OUTPUT LOG"""
objFile.WriteLine "$lLogHdr.Font      = New-Object Drawing.Font(""Segoe UI"", 7.5, [Drawing.FontStyle]::Bold)"
objFile.WriteLine "$lLogHdr.ForeColor = $cDim"
objFile.WriteLine "$lLogHdr.BackColor = [Drawing.Color]::FromArgb(18, 18, 22)"
objFile.WriteLine "$lLogHdr.Dock      = ""Top"""
objFile.WriteLine "$lLogHdr.Height    = 22"
objFile.WriteLine "$lLogHdr.TextAlign = ""MiddleLeft"""
objFile.WriteLine "$pRight.Controls.Add($lLogHdr) | Out-Null   # <-- Top first"
objFile.WriteLine ""
objFile.WriteLine "$logBox            = New-Object Windows.Forms.RichTextBox"
objFile.WriteLine "$logBox.Dock       = ""Fill"""
objFile.WriteLine "$logBox.BackColor  = $cLog"
objFile.WriteLine "$logBox.ForeColor  = $cFG"
objFile.WriteLine "$logBox.Font       = $fMono"
objFile.WriteLine "$logBox.ReadOnly   = $true"
objFile.WriteLine "$logBox.BorderStyle = ""None"""
objFile.WriteLine "$logBox.ScrollBars = ""Vertical"""
objFile.WriteLine "$logBox.WordWrap   = $true"
objFile.WriteLine "$pRight.Controls.Add($logBox) | Out-Null     # <-- Fill second"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# STATUS BAR"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$statusStrip           = New-Object Windows.Forms.StatusStrip"
objFile.WriteLine "$statusStrip.BackColor = $cStatus"
objFile.WriteLine "$statusStrip.SizingGrip = $false"
objFile.WriteLine ""
objFile.WriteLine "$statusLabel           = New-Object Windows.Forms.ToolStripStatusLabel"
objFile.WriteLine "$statusLabel.Text      = ""Ready"""
objFile.WriteLine "$statusLabel.ForeColor = $cWhite"
objFile.WriteLine "$statusLabel.Font      = $fSm"
objFile.WriteLine "[void]$statusStrip.Items.Add($statusLabel)"
objFile.WriteLine ""
objFile.WriteLine "$statusPath           = New-Object Windows.Forms.ToolStripStatusLabel"
objFile.WriteLine "$statusPath.Text      = ""Report: $ReportPath"""
objFile.WriteLine "$statusPath.ForeColor = [Drawing.Color]::FromArgb(150, 195, 255)"
objFile.WriteLine "$statusPath.Font      = $fSm"
objFile.WriteLine "$statusPath.Spring    = $true"
objFile.WriteLine "$statusPath.TextAlign = ""MiddleRight"""
objFile.WriteLine "[void]$statusStrip.Items.Add($statusPath)"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# ASSEMBLE FORM"
objFile.WriteLine "# (Add Fill panels before Left panels; Controls added last paint on top)"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$form.Controls.Add($pRight)"
objFile.WriteLine "$form.Controls.Add($pLeft)"
objFile.WriteLine "$form.Controls.Add($statusStrip)"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# LOG HELPERS  (UI thread only - called from timer tick)"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "function Append-Log([string]$Text, [Drawing.Color]$Color) {"
objFile.WriteLine "    $logBox.SelectionStart  = $logBox.TextLength"
objFile.WriteLine "    $logBox.SelectionLength = 0"
objFile.WriteLine "    $logBox.SelectionColor  = $Color"
objFile.WriteLine "    $logBox.AppendText($Text + ""`n"")"
objFile.WriteLine "    $logBox.SelectionColor  = $cFG"
objFile.WriteLine "    $logBox.ScrollToCaret()"
objFile.WriteLine "}"
objFile.WriteLine ""
objFile.WriteLine "function Show-QueuedMessage([string]$Msg) {"
objFile.WriteLine "    if ($Msg.Length -ge 2 -and $Msg[1] -eq '|') {"
objFile.WriteLine "        $col = switch ($Msg[0]) {"
objFile.WriteLine "            'H' { $cCyan  }"
objFile.WriteLine "            'P' { $cGreen }"
objFile.WriteLine "            'F' { $cRed   }"
objFile.WriteLine "            'E' { $cRed   }"
objFile.WriteLine "            'D' { $cDim   }"
objFile.WriteLine "            default { $cFG }"
objFile.WriteLine "        }"
objFile.WriteLine "        Append-Log $Msg.Substring(2) $col"
objFile.WriteLine "    } else {"
objFile.WriteLine "        Append-Log $Msg $cFG"
objFile.WriteLine "    }"
objFile.WriteLine "}"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# POLLING TIMER - drains queue, detects task completion"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$pollingTimer          = New-Object Windows.Forms.Timer"
objFile.WriteLine "$pollingTimer.Interval = 80"
objFile.WriteLine "$pollingTimer.Add_Tick({"
objFile.WriteLine "    $msg = """""
objFile.WriteLine "    while ($script:MsgQueue.TryDequeue([ref]$msg)) { Show-QueuedMessage $msg }"
objFile.WriteLine ""
objFile.WriteLine "    if ($script:IsBusy -and $null -ne $script:Handle -and $script:Handle.IsCompleted) {"
objFile.WriteLine "        # Drain any remaining messages"
objFile.WriteLine "        while ($script:MsgQueue.TryDequeue([ref]$msg)) { Show-QueuedMessage $msg }"
objFile.WriteLine ""
objFile.WriteLine "        if ($script:PSInst.HadErrors) {"
objFile.WriteLine "            Append-Log """" $cFG"
objFile.WriteLine "            Append-Log ""[!] One or more steps reported errors - see report for details."" $cRed"
objFile.WriteLine "        } else {"
objFile.WriteLine "            Append-Log """" $cFG"
objFile.WriteLine "            Append-Log ""Done."" $cGreen"
objFile.WriteLine "        }"
objFile.WriteLine "        Append-Log ""Report: $ReportPath"" $cDim"
objFile.WriteLine "        Append-Log (""-"" * 68) $cSep"
objFile.WriteLine ""
objFile.WriteLine "        # Cleanup"
objFile.WriteLine "        try { $script:PSInst.Dispose()                          } catch {}"
objFile.WriteLine "        try { $script:RS.Close(); $script:RS.Dispose()          } catch {}"
objFile.WriteLine "        $script:PSInst  = $null"
objFile.WriteLine "        $script:RS      = $null"
objFile.WriteLine "        $script:Handle  = $null"
objFile.WriteLine "        $script:IsBusy  = $false"
objFile.WriteLine ""
objFile.WriteLine "        $statusLabel.Text = ""Ready"""
objFile.WriteLine "        foreach ($b in $script:AllButtons) { $b.Enabled = $true }"
objFile.WriteLine "    }"
objFile.WriteLine "})"
objFile.WriteLine "$pollingTimer.Start()"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# FORM CLOSING"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "$form.Add_FormClosing({"
objFile.WriteLine "    $pollingTimer.Stop()"
objFile.WriteLine "    if ($script:PSInst) { try { $script:PSInst.Dispose()               } catch {} }"
objFile.WriteLine "    if ($script:RS)     { try { $script:RS.Close(); $script:RS.Dispose() } catch {} }"
objFile.WriteLine "})"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# WELCOME LOG"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "Initialize-Report"
objFile.WriteLine ""
objFile.WriteLine "Append-Log ""Simple System Health Tool  v3.1"" $cCyan"
objFile.WriteLine "Append-Log ""Computer : $($env:COMPUTERNAME)   $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"" $cDim"
objFile.WriteLine "Append-Log ""Report   : $ReportPath"" $cDim"
objFile.WriteLine "Append-Log (""-"" * 68) $cSep"
objFile.WriteLine "Append-Log ""Select an operation from the left panel to begin."" $cFG"
objFile.WriteLine "Append-Log """" $cFG"
objFile.WriteLine ""
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "# RUN"
objFile.WriteLine "# =============================================================================="
objFile.WriteLine "[Windows.Forms.Application]::Run($form)"

objFile.Close
Set objFile = Nothing

' Launch the PS1 hidden (no console window) - same as original launcher
Dim strCmd
strCmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & strPS1 & """"
objShell.Run strCmd, 0, False

Set objShell = Nothing
Set objFSO   = Nothing